[".config/zsh/fzf-git.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf-git.sh/main/fzf-git.sh"
    refreshPeriod = "168h"  # 1 week

[".local/share/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"  # 1 week

[".config/alacritty/catppuccin-macchiato.toml"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/alacritty/main/catppuccin-macchiato.toml"
    refreshPeriod = "168h"  # 1 week
