[".config/zsh/fzf-completions.zsh"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf/refs/heads/master/shell/completion.zsh"
    refreshPeriod = "168h"  # 1 week

[".config/zsh/fzf-git.sh"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/fzf-git.sh/main/fzf-git.sh"
    refreshPeriod = "168h"  # 1 week

[".local/share/tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"  # 1 week

[".config/alacritty/catppuccin-macchiato.toml"]
    type = "file"
    url = "https://raw.githubusercontent.com/catppuccin/alacritty/main/catppuccin-macchiato.toml"
    refreshPeriod = "168h"  # 1 week

[".config/bat/themes"]
    type = "archive"
    url = "https://github.com/catppuccin/bat/archive/master.tar.gz"
    exact = true
    stripComponents = 2
    refreshPeriod = "168h"
    #include = ["*/themes/Catppuccin Frappe.tmThem", "**/Catppuccin Macchiato.tmThem"]
    include = ["*/themes/**"]
    #path = "themes"
