[[keyboard.bindings]]
chars = "\u0017w"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017r"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017t"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017h"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0017,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00171"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00172"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00173"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00174"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00175"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00176"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00177"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00178"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00179"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017\u001B[D"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017\u001B[B"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017\u001B[A"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017\u001B[C"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017;"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017{"
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017}"
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0017\u001B[1;5D"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0017\u001B[1;5B"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0017\u001B[1;5A"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0017\u001B[1;5C"
key = "Right"
mods = "Command|Shift"
