name: Pre-commit check

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --from-ref origin/main --to-ref HEAD
